package App.Kelas_8;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JTextField;
import konfigurasi.CONFIG;

public class Dashboard8 extends javax.swing.JFrame {
    
    public Dashboard8() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Input = new javax.swing.JButton();
        Riwayat = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        Edit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 51));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(390, 319));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("DASHBOARD SCOSA");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 10, 250, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("WELCOME");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 60, 91, 16);

        UserName1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UserName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserName1.setText("Walikelas 8");
        jPanel1.add(UserName1);
        UserName1.setBounds(20, 90, 370, 22);

        Input.setText("Input Absensi");
        Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputActionPerformed(evt);
            }
        });
        jPanel1.add(Input);
        Input.setBounds(30, 180, 117, 25);

        Riwayat.setText("Riwayat Absensi");
        Riwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiwayatActionPerformed(evt);
            }
        });
        jPanel1.add(Riwayat);
        Riwayat.setBounds(230, 180, 125, 25);

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        jPanel1.add(Keluar);
        Keluar.setBounds(230, 260, 125, 25);

        Edit.setText("Edit Absensi");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        jPanel1.add(Edit);
        Edit.setBounds(30, 260, 117, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiwayatActionPerformed
       Riwayat_Absen8 RA=new Riwayat_Absen8();
       RA.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_RiwayatActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        this.dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    private void InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputActionPerformed
        Input_Absen8 IA=new Input_Absen8();
        IA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InputActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        Edit_Absen8 EA=new Edit_Absen8();
        EA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EditActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit;
    private javax.swing.JButton Input;
    private javax.swing.JButton Keluar;
    private javax.swing.JButton Riwayat;
    public static final javax.swing.JLabel UserName1 = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
